name: github-actions-on-pull-request

on:
  pull_request:
    types:
      - opened
    branches:
      - 'develop'
      - 'main'

jobs:
    test:
      runs-on: ubuntu-latest
      timeout-minutes: 5
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Go
          uses: actions/setup-go@v4
          with:
            go-version: '>=1.22.0'
            cache: false
        
        - name: OS Version
          run: cat /etc/os-release
        
        - name: Go Version
          run: go version
        
        - name: Test pkgs/
          run: |
            cd pkgs && go test -v ./... && cd ..

    build:
      runs-on: ubuntu-latest
      timeout-minutes: 5
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Go
          uses: actions/setup-go@v4
          with:
            go-version: '>=1.22.0'
            cache: false

        - name: OS Version
          run: cat /etc/os-release

        - name: Go Version
          run: go version

        - name: Build
          run: |
            mkdir ./bin
            sh ./scripts/futaba/build.sh
            sh ./scripts/hitoha/build.sh
            sh ./scripts/karakuri/build.sh
    
    exec_test:
      runs-on: ubuntu-latest
      timeout-minutes: 5
      needs: build
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Go
          uses: actions/setup-go@v4
          with:
            go-version: '>=1.22.0'
            cache: false

        - name: OS Version
          run: cat /etc/os-release

        - name: Go Version
          run: go version

        - name: Build
          run: |
            mkdir ./bin
            sh ./scripts/futaba/build.sh
            sh ./scripts/hitoha/build.sh
            sh ./scripts/karakuri/build.sh
        
        - name: Setup Hitoha
          run: ./bin/hitoha &
        
        - name: Run Hello-World
          run: ./bin/karakuri run --it --image hello-world --rm
